theme = "primordial"

[fonts]
monospace_path = "C:/Users/charl/Downloads/VictorMono/VictorMonoNerdFontMono-Regular.ttf"
symbols_path = "C:/Users/charl/Downloads/Terminus/TerminessNerdFontMono-Regular.ttf"

[grid]
mode = "fixed"

[os.windows]
blur = true

[window]
edge_style = "beveled"
corner_style = "g3"
radius = 24.0
inset = 0.0

[ui]
top_margin = 0.0
tab_bar_mode = "fixed"
background_mode = "reveal"
